quiz/core/urls.py
from django.urls import path
from .views import (
    Test,
    CreateQuiz,
    CreateQuestion,
    AttemptQuiz,
    Result,
    RecordResponse,
    Attempt,
    DeleteQuestion,
    EditQuiz,
    EditQuestion,
    UserQuizRecord,
)

app_name = 'core'

urlpatterns = [
    path('test/', Test.as_view(), name='test'),
    path('create/', CreateQuiz.as_view(), name = 'create'),
    path('edit/<slug>/', EditQuiz.as_view(), name = 'edit_quiz'),

    path('<slug>/create/question/', CreateQuestion.as_view(), name = 'create_question'),
    path('question/<slug>/delete/<id>/', DeleteQuestion.as_view(), name = "delete_question"),
    path('question/<slug>/update/<id>/', EditQuestion.as_view(), name = "edit_question"),

    path('record/user/<slug>', UserQuizRecord.as_view(), name= 'user_quiz_record'),

    path('attempt/<slug>/', AttemptQuiz.as_view(), name = 'attempt_quiz'),
    path('attempt1/<slug>/<int:id>/<int:index>/', Attempt.as_view(), name = 'attempt'),

    path('result/<slug>/<id>/', Result.as_view(), name = 'quiz_result'),
    path('record_response/', RecordResponse.as_view(), name = 'ajax_record_response'),

]

quiz/profiles/urls.py
from django.urls import path,include
from . import views

app_name='profiles'

urlpatterns = [
    path('edit/',views.ProfileUpdate.as_view() , name='profile_update'),
    path('image-edit/',views.DpUpdate.as_view() , name='dp_update'),
    path('<slug>',views.ProfileView.as_view() , name='profile'),
]

quiz/quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import (
     Home,
     about,
     Setting,
     Activity,
     Completed,
     Created,
     autoCompleteView,
     searchAutoComplete,
     Search,

)

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('profile/',include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('quiz/', include("core.urls")),
    path('about/', about , name = 'about'),
    path('settings/', Setting.as_view(), name='setting'),
    path('activity/', Activity.as_view(), name= 'activity'),
    path('completed/', Completed.as_view(), name= 'completed'),
    path('created/', Created.as_view(), name = 'created'),

    path('search/', Search.as_view(), name='search'),
    path('autocomplete/', autoCompleteView, name='autocomplete'),
    path('search-autocomplete/', searchAutoComplete, name='search-autocomplete'),
    path('', Home.as_view(), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

quiz/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    GENDER = [
        ('M','Male'),
        ('F','Female'),
        ('PNS','Prefer Not To Say'),
        ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    role = models.CharField(max_length=50, blank=True)
    website = models.CharField(max_length=200, blank=True)
    bio = models.TextField(blank=True)
    gender = models.CharField(max_length=3, choices = GENDER,default='PNS')
    dob = models.DateField(null=True,auto_now_add=False, blank=True)
    linkedin = models.CharField(max_length=500, blank=True)
    twitter = models.CharField(max_length=500, blank=True)
    github = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

class Profileimage(models.Model):
    # background_image = models.ImageField(default='default_bg.png', blank=True , upload_to = 'background_images')
    profile_image = models.ImageField(default='default_dp.png', blank=True , upload_to = 'profile_images')
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return str(self.user)

quiz/profiles/forms.py
from PIL import Image
from django.core.files import File
from django import forms
from . import models
from django.contrib.auth.models import User
from . models import Profile , Profileimage

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('role' ,'gender','website','bio' ,'dob','linkedin' ,'twitter' ,'github',)


class DpForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Profileimage
        fields = ('profile_image', 'x', 'y', 'width', 'height',)

    def save(self):
        photo = super(DpForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.profile_image)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.profile_image.path)

        return photo

quiz/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.models import User

from .models import Profile , Profileimage
from . forms import UserForm , ProfileForm, DpForm


from core.models import Quiz


decorators = [login_required(login_url = "/accounts/login/")]
decorators_1 = [transaction.atomic] + decorators



@method_decorator(decorators , name='dispatch')
class ProfileView(View):

    def get(self, request, slug):
        instance = User.objects.get(username=slug)
        id = instance.id
        profile = Profile.objects.get(user=id)
        quizes = Quiz.objects.filter(author = instance)
        instance = request.user
        data = {'profile':profile , 'user':instance , 'quizes' : quizes}
        return render(request,'profiles/profile_view.html',data)


@method_decorator(decorators_1 , name='dispatch')
class ProfileUpdate(View):

    def get(self, request):
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

        context={
        'user_form': user_form,
        'profile_form': profile_form,
        }

        return render(self.request, 'profiles/profile_update.html', context )

    def post(self,request):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile )

        if user_form.is_valid() and profile_form.is_valid():
            instance = user_form.save(commit=False)
            instance = instance.username
            user_form.save()

            profile_instance = profile_form.save(commit=False)
            profile_instance.save()

            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('profiles:profile',slug = instance )
        else:
            context={
            'user_form': user_form,
            'profile_form': profile_form,
            }
            messages.error(request, ('Please correct the error below.'))
            return render(self.request, 'profiles/profile_update.html', context )

class DpUpdate(View):
    def get(self, request):
        form = DpForm(instance = request.user)

        context = {
        'form' : form,
        }
        return render(self.request, 'profiles/dp_update.html', context)

    def post(self, request):
        form = DpForm(request.POST,request.FILES ,instance=request.user.profileimage)
        if form.is_valid():
            form.save()
            return redirect('profiles:dp_update')
        else:
            messages.error(request, ('Update was unsuccessful'))
            context = {
            'form' : form,
            }
            return render(self.request, 'profiles/dp_update.html', context)

quiz/profiles/templates/profiles/dp_update.html
{% extends "settings-base.html" %}
{% block custom_js %}
<script>
  $(function() {

    /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
    $("#id_profile_image").change(function() {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          $("#image").attr("src", e.target.result);
          $("#modalCrop").modal("show");
        }
        reader.readAsDataURL(this.files[0]);
      }
    });

    /* SCRIPTS TO HANDLE THE CROPPER BOX */
    var $image = $("#image");
    var cropBoxData;
    var canvasData;
    $("#modalCrop").on("shown.bs.modal", function() {
      $image.cropper({
        viewMode: 1,
        aspectRatio: 1 / 1,
        minCropBoxWidth: 200,
        minCropBoxHeight: 200,
        ready: function() {
          $image.cropper("setCanvasData", canvasData);
          $image.cropper("setCropBoxData", cropBoxData);
        }
      });
    }).on("hidden.bs.modal", function() {
      cropBoxData = $image.cropper("getCropBoxData");
      canvasData = $image.cropper("getCanvasData");
      $image.cropper("destroy");
    });

    $(".js-zoom-in").click(function() {
      $image.cropper("zoom", 0.1);
    });

    $(".js-zoom-out").click(function() {
      $image.cropper("zoom", -0.1);
    });

    /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
    $(".js-crop-and-upload").click(function() {
      var cropData = $image.cropper("getData");
      $("#id_x").val(cropData["x"]);
      $("#id_y").val(cropData["y"]);
      $("#id_height").val(cropData["height"]);
      $("#id_width").val(cropData["width"]);
      $("#Upload").submit();
    });

  });
</script>
{% endblock %}

{% block settings-content %}
<div class="profile-image">
  <div class="col-md-8 offset-md-2">
    <div>
      <div class="avatar">
        <img src="{{ user.profileimage.profile_image.url }}" class="img-raised rounded-circle img-fluid">
      </div>
      <div class="card-2">
        <form action="{% url 'profiles:dp_update' %}" method="POST" enctype="multipart/form-data" id='Upload'>
          {% csrf_token %}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Image</legend>
            {{form}}
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Crop the photo</h4>
      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            <span class="glyphicon glyphicon-zoom-in"></span>
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            <span class="glyphicon glyphicon-zoom-out"></span>
          </button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

quiz/profiles/templates/profiles/profile_update.html
{% extends "settings-base.html" %}
{% block settings-content %}
<div class="content-section">
  <form action="{% url 'profiles:profile_update' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      {{ user_form}}
      {{ profile_form}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Submit</button>
    </div>
  </form>
</div>
{% endblock %}

quiz/profiles/templates/profiles/profile_view.html
{% extends 'base.html' %}
{% load static %}
{% block content1 %}
<figure class="figure profile">
  <div class="profile-bg"><img class="img-fluid" src="https://picsum.photos/2000/1000?grayscale"></div>
</figure>
<div class="profile profile-rise">
  <div class="profile-content">
    <div class="profile-des">
      <div class="jumbotron index-profile">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div>
              <div class="avatar">
                <img src="{{ profile.user.profileimage.profile_image.url }}" class="img-raised rounded-circle img-fluid">
              </div>
              <div class="card-2">
                <div class="name">
                  <h3 class="center">{{ profile.user }}</h3>
                  {% if profile.role %}
                  <h6 class="center">{{ profile.role }}</h6>
                  {% endif %}
                  <div class="center">
                    {% if profile.user.email %}
                    <a href="mailto:{{ profile.user.email }}" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-envelope-square" aria-hidden="true"></i></a>
                    {% endif %}
                    {% if profile.linkedin %}
                    <a href="{{ profile.linkedin }}" class="btn btn-just-icon btn-link btn-linkedin"><i class="fa fa-linkedin"></i></a>
                    {% endif %}
                    {% if profile.twitter %}
                    <a href="{{ profile.twitter }}" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                    {% endif %}
                    {% if profile.github %}
                    <a href="{{ profile.github }}" class="btn btn-just-icon btn-link btn-github"><i class="fa fa-github"></i></a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <p class="about" align="center">{{ profile.bio }}</p>
        <div class="following">
          <div class="following">
            <div class="btn-group btn-action-label" role="group" aria-label="Like">
              <button type="button" class="btn btn-sm btn-secondary btn-action">
                <span>Quizes</span>
              </button>
              <a href="#" class="btn btn-sm btn-outline-secondary btn-label">{{ quizes|length}}</a>
            </div>
          </div>
        </div>
        <hr>
        <div class="header-2"><i class="fa fa-th-large" aria-hidden="true"> Created quizes</i></div>
        <div class="card-columns">
          {% for quiz in quizes %}
          <div class="card">
            {% if quiz.image %}
            <img src="{{ quiz.image.url }}" class="card-img-top" alt="quiz_image">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ quiz.title }}</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
            <div class="card-footer">
            {% if request.user == quiz.author %}
              <button type="button" class="btn btn-warning btn-sm" onclick="location.href='{% url 'core:edit_quiz' quiz.slug %}';" >
                <span class="glyphicon glyphicon-pencil"></span>Edit
              </button>
            {% else %}
            <form method="post" action="{% url 'core:attempt_quiz' quiz.slug %}" class="js-quiz-form">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning btn-sm" >
                <span class="glyphicon glyphicon-pencil"></span>Attempt
              </button>
            </form>
            {% endif %}
          </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}