quiz/core/urls.py
from django.urls import path
from .views import (
    Test,
    CreateQuiz,
    CreateQuestion,
    AttemptQuiz,
    Result,
    RecordResponse,
    Attempt,
    DeleteQuestion,
    EditQuiz,
    EditQuestion,
    UserQuizRecord,
)

app_name = 'core'

urlpatterns = [
    path('test/', Test.as_view(), name='test'),
    path('create/', CreateQuiz.as_view(), name = 'create'),
    path('edit/<slug>/', EditQuiz.as_view(), name = 'edit_quiz'),

    path('<slug>/create/question/', CreateQuestion.as_view(), name = 'create_question'),
    path('question/<slug>/delete/<id>/', DeleteQuestion.as_view(), name = "delete_question"),
    path('question/<slug>/update/<id>/', EditQuestion.as_view(), name = "edit_question"),

    path('record/user/<slug>', UserQuizRecord.as_view(), name= 'user_quiz_record'),

    path('attempt/<slug>/', AttemptQuiz.as_view(), name = 'attempt_quiz'),
    path('attempt1/<slug>/<int:id>/<int:index>/', Attempt.as_view(), name = 'attempt'),

    path('result/<slug>/<id>/', Result.as_view(), name = 'quiz_result'),
    path('record_response/', RecordResponse.as_view(), name = 'ajax_record_response'),

]

quiz/quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import (
     Home,
     about,
     Setting,
     Activity,
     Completed,
     Created,
     autoCompleteView,
     searchAutoComplete,
     Search,

)

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('profile/',include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('quiz/', include("core.urls")),
    path('about/', about , name = 'about'),
    path('settings/', Setting.as_view(), name='setting'),
    path('activity/', Activity.as_view(), name= 'activity'),
    path('completed/', Completed.as_view(), name= 'completed'),
    path('created/', Created.as_view(), name = 'created'),

    path('search/', Search.as_view(), name='search'),
    path('autocomplete/', autoCompleteView, name='autocomplete'),
    path('search-autocomplete/', searchAutoComplete, name='search-autocomplete'),
    path('', Home.as_view(), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

quiz/core/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.shortcuts import  get_object_or_404


QUESTION_TYPE = [
    ('MCQ' , 'multiple_choices'),
    ('C-Box', 'checkboxe'),
]

class Quiz(models.Model):
    author = models.ForeignKey(User, default=None, on_delete = models.SET_NULL, null =True)
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to = 'quiz_banner',
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field",
            default='default.jpg')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_total_no_of_questions(self):
        questions_count = len(Question.objects.filter(quiz = self))
        return questions_count

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, default=None, on_delete = models.SET_NULL, null = True)
    type = models.CharField(choices = QUESTION_TYPE, max_length = 10)
    question = models.CharField(max_length  = 1000, null = False)
    image = models.ImageField(upload_to = 'question_banner',
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    time = models.IntegerField(default = 45)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return str(self.id)

    def get_options(self):
        options = Option.objects.filter(question=self)
        return options


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE,null = True)
    answer = models.BooleanField(default = False)
    option  = models.CharField(max_length = 400, blank = True)

    def __str__(self):
        # return 'q-'+ str(self.question.id) +'--'+self.option
        return str(self.id)

class Record(models.Model):
    user = models.ForeignKey(User, default = None, on_delete = models.SET_NULL, null = True)
    quiz = models.ForeignKey(Quiz, default = None, on_delete = models.SET_NULL, null = True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    questions = ArrayField(models.IntegerField(default = list))
    key = ArrayField(models.CharField(max_length=400, default=None))

    def __str__(self):
        s=''
        for i in self.questions:
            s +=str(i)+', '
        s = s[:-2]
        return s

    def get_record(self):
        record = get_object_or_404(Record, record=self)
        return record

class Response(models.Model):
    record = models.ForeignKey(Record, default = None, on_delete = models.CASCADE)
    answers = ArrayField(models.CharField(max_length=400, default=None, null = True))
    total_questions = models.IntegerField(default = 0)
    correct = models.IntegerField(default=0)

    def get_quiz(self):
        record = get_object_or_404(Record, record = self.record)
        quiz = get_object_or_404(Quiz, quiz = record.quiz)
        return quiz

quiz/core/forms.py
from django import forms
from django.forms import modelformset_factory

from .models import (
    Quiz,
    Question,
    Option,
)


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title','image']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['type','question', 'time']

class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ['answer', 'option',]


optionformset = modelformset_factory(
    Option,
    fields = ['answer' , 'option']
)

quiz/core/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.template.loader import render_to_string
from django.views import View

from datetime import datetime

from .forms import (
    QuizForm,
    QuestionForm,
    OptionForm,
    optionformset,
)
from .models import (
    Quiz,
    Question,
    Record,
    Option,
    Response,
)


class Test(View):
    def get(self, request):
        test = "hell no"
        context = {
            'test':test,
        }
        return render(request, 'core/test.html', context)

class CreateQuiz(View):
    def get(self, request):
        quizform = QuizForm(request.GET or None)
        context = {
            'form': quizform,
        }
        return render(request, 'core/create.html',context)

    def post(self, request):
        quizform = QuizForm(request.POST or None)

        if quizform.is_valid():
            quiz = quizform.save(commit = False)
            quiz.author = request.user
            if 'image' in request.FILES:
                quiz.image = request.FILES['image']
            quiz.save()
        else :
            message.error(request,('please correct the below errrors'))
            context = {
                'form' : quizform,
                }
            return render(self.request, 'core/create.html', context)
        return redirect('core:edit_quiz', slug = quiz.slug)



class EditQuiz(View):
    def get(self, request, slug):
        quiz = get_object_or_404(Quiz, slug=slug)
        questions = Question.objects.filter(quiz = quiz)

        context = {
            'quiz' : quiz,
            'questions' : questions,
        }
        return render(self.request, 'core/quiz_edit.html', context)


class CreateQuestion(View):
    # handle the image of the question
    def get(self, request, slug):
        quiz = get_object_or_404(Quiz, slug = slug)
        questionform = QuestionForm(request.GET or None)
        formset = optionformset(queryset = Option.objects.none())
        context = {
            'questionform' : questionform,
            'formset' : formset,
            'quiz' : quiz,
        }
        html_code = render_to_string('core/partial_question_create.html', context, request = request)
        return JsonResponse({ 'html_code' : html_code })

    def post(self, request, slug):
        data = dict()
        quiz = get_object_or_404(Quiz, slug = slug)
        formset = optionformset(request.POST)
        question = QuestionForm(request.POST)
        if question.is_valid() and formset.is_valid():
            question = question.save(commit=False)
            question.quiz = quiz
            question.save()
            for form in formset:
                option = form.save(commit=False)
                if option.option:
                    option.question = question
                    option.save()
            data['form_is_valid'] = True
            questions = Question.objects.filter(quiz = quiz)
            context={
              'questions' : questions,
              'quiz' : quiz,
            }
            data['html_code'] = render_to_string('core/partial_question_list.html', context, request = request)
        else:
            data['form_is_valid'] = False
            context = {
                'quiz' : quiz,
                'questionform' : questionform,
                'formset' : formset,
            }
            data['html_code'] = render_to_string('core/partial_question_create.html', context, request=request)
        return JsonResponse(data)

class DeleteQuestion(View):
    def get(self, request, slug, id):
        data = dict()
        question = get_object_or_404(Question, id = id)
        quiz = get_object_or_404(Quiz, slug = slug)
        context = {
            'question' : question,
            'quiz' : quiz,
        }
        data['html_code'] = render_to_string('core/partial_question_delete.html', context, request=request)
        return JsonResponse(data)

    def post(self, request, slug, id):
        data = dict()
        question = get_object_or_404(Question, id = id)
        quiz = get_object_or_404(Quiz, slug = slug)
        question.delete()
        data['form_is_valid'] = True
        questions = Question.objects.filter(quiz = quiz)
        context={
          'questions' : questions,
          'quiz' : quiz,
        }
        data['html_code'] = render_to_string('core/partial_question_list.html', context, request = request)
        return JsonResponse(data)


class EditQuestion(View):
    def get(self, request, slug, id):
        data = dict()
        quiz = get_object_or_404(Quiz, slug = slug)
        question = get_object_or_404(Question,id = id)
        questionform = QuestionForm(instance = question)
        formset = optionformset(queryset = Option.objects.filter(question = question))
        context = {
            'quiz' : quiz,
            'questionform' : questionform,
            'formset' : formset,
            'question' : question,
        }
        html_code = render_to_string('core/partial_question_update.html', context, request = request)
        return JsonResponse({ 'html_code' : html_code })


    def post(self, request, slug, id):
        pass

# class AttemptQuiz(View):
#     def get(self, request, slug):
#         quiz = get_object_or_404(Quiz, slug=slug)
#         questions  = Question.objects.filter(quiz=quiz).order_by('?')
#         questions_order = []
#         for i in questions:
#             questions_order.append(i.id)
#         # # resume feature
#         # try:
#         #     record = Record.objects.filter(quiz=quiz, user=request.user).latest('timestamp')
#         #     if datetime.now()-record.timestamp:
#
# # attempt quiz if atleast one question exists
#
#         record = Record(user = request.user, quiz=quiz, questions=questions_order)
#         key =[]
#         for i in questions:
#             options = Option.objects.filter(question=i)
#             for option in options:
#                 if option.answer:
#                     key.append(option.option)
#         record.key = key
#         record.save()
#
#         context ={
#             'questions' : questions,
#             'quiz' : quiz,
#         }
#         # return render(self.request, 'core/quiz_attempt.html', context)
#         return redirect('core:attempt', slug = quiz.slug, id=record.id, index=1)
#
#     def post(self, request, slug):
#         form = request.POST
#         answers =[]
#         for key,value in form.items():
#             if key != 'csrfmiddlewaretoken' and key != 'button':
#                 answers.append(value)
#         quiz = get_object_or_404(Quiz, slug = slug)
#         record = Record.objects.filter(quiz=quiz, user=request.user).latest('timestamp')
#         correct_count = 0
#         for i in range(len(record.key)):
#             if record.key[i] == answers[i]:
#                 correct_count +=1
#         response = Response(record = record, answers = answers, total_questions = quiz.get_total_no_of_questions(), correct = correct_count )
#         response.save()
#         return redirect('core:quiz_result', slug = quiz.slug, id=record.id)
#
#
# class Attempt(View):
#     def get(self, request, slug, id, index):
#         quiz  = get_object_or_404(Quiz, slug = slug)
#         record = get_object_or_404(Record, id = id)
#         question = get_object_or_404(Question, id = record.questions[index-1])
#         number = len(record.questions)
#         index += 1
#         context = {
#             'quiz' : quiz,
#             'record' : record,
#             'question' : question,
#             'index' : index,
#             'number' : number,
#         }
#         return render(self.request, 'core/attempt.html', context)
#
#     def post(self, request, slug, id, index):
#         record = get_object_or_404(Record, id = id)
#         for key,value in request.POST.items():
#             if key != 'csrfmiddlewaretoken' and key != 'button':
#                 answer = value
#         try :
#             response = get_object_or_404(Response, record = record)
#             response.answers.append(answer)
#         except :
#             response = Response(record = record,answers = [answer])
#         response.save()
#         if index <= len(record.questions):
#             return redirect('core:attempt', slug = slug, id=id, index = index)
#         else:
#             count = 0
#             for i in range(len(record.key)):
#                 if record.key[i] == response.answers[i]:
#                     count +=1
#             response.correct = count
#             response.total_questions = len(record.key)
#         response.save()
#         return redirect('core:quiz_result', slug = slug, id=record.id)

class AttemptQuiz(View):
    def get(self, request, slug):
        data = dict()
        quiz = get_object_or_404(Quiz, slug=slug)
        records = Record.objects.filter(quiz=quiz,user=request.user).order_by('timestamp')
        responses = Response.objects.none()
        for record in records:
            response = Response.objects.filter(record=record)
            responses = responses.union(response)
        responses = responses.order_by('-correct')[:3]

        records = Record.objects.filter(quiz=quiz).order_by('timestamp')
        responses_all = Response.objects.none()
        for record in records:
            response = Response.objects.filter(record=record)
            responses_all = responses_all.union(response)
        responses_all = responses_all.order_by('-correct')[:10]

        context = {
            'quiz' : quiz,
            'responses_all' : responses,
            'responses' : responses_all,
        }
        data['html_code'] = render_to_string('core/partial_quiz_attempt.html', context, request=request)
        return JsonResponse(data)


    def post(self, request, slug):

quiz/core/templates/core/attempt.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>Quiz details</h1>
  <h6>{{ quiz.title }} <br>{{ quiz.id }}--{{ quiz.slug }}</h6>
  <div class="container">
    <form action="{% url 'core:attempt' slug=quiz.slug id=record.id index=index %}" method="post">
      {% csrf_token %}
      {{question.question}} <br>
      <div class="container">
        {% for option in question.get_options %}
        <input type="radio" id="{{option.id}}" name={{question.id}} value="{{ option.option }}" required>
        <label for="{{option.id}}">{{option.option}}</label><br>
        {% endfor %}
      </div>
      {% if number < index %}
      <button type="submit" name="button">Submit</button>
      {% else %}
      <button type="submit" name="button">Next</button>
      {% endif %}
    </form>
  </div>
</div>
{% endblock %}

quiz/core/templates/core/attempt1.html
{% extends 'empty_base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/ready.compiled2.css' %}">
<link rel="stylesheet" href="{% static 'css/quiz-question.css' %}">
<link rel="stylesheet" href="{% static 'css/button1.css' %}">
<link rel="stylesheet" href="{% static 'css/timer1.css' %}">
<link rel="stylesheet" href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1462889/unicons.css">
{% endblock %}
{% block content %}
<div class="demo" id="hideDiv">
  <div class="demo__colored-blocks">
    <div class="demo__colored-blocks-rotater">
      <div class="demo__colored-block"></div>
      <div class="demo__colored-block"></div>
      <div class="demo__colored-block"></div>
    </div>
    <div class="demo__colored-blocks-inner"></div>
    <div class="demo__text">Ready</div>
  </div>
  <div class="demo__inner">
    <svg class="demo__numbers" viewBox="0 0 100 100">
      <defs>
        <path class="demo__num-path-1" d="M40,28 55,22 55,78" />
        <path class="demo__num-join-1-2" d="M55,78 55,83 a17,17 0 1,0 34,0 a20,10 0 0,0 -20,-10" />
        <path class="demo__num-path-2" d="M69,73 l-35,0 l30,-30 a16,16 0 0,0 -22.6,-22.6 l-7,7" />
        <path class="demo__num-join-2-3" d="M28,69 Q25,44 34.4,27.4" />
        <path class="demo__num-path-3" d="M30,20 60,20 40,50 a18,15 0 1,1 -12,19" />
      </defs>
      <path class="demo__numbers-path" d="M-10,20 60,20 40,50 a18,15 0 1,1 -12,19
               Q25,44 34.4,27.4
               l7,-7 a16,16 0 0,1 22.6,22.6 l-30,30 l35,0 L69,73
               a20,10 0 0,1 20,10 a17,17 0 0,1 -34,0 L55,83
               l0,-61 L40,28" />
    </svg>
  </div>
</div>
<div id="question">
</div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
  $(function() {
    setTimeout(function() {
      $("#hideDiv").fadeOut(200);
      $.ajax({
        url: "{% url "core:attempt" quiz.slug record.id 1 %}",
        type: 'get',
        dataType: 'json',
        success: function(data) {
        $("#question").html(data.html_code);
        }
      });
    }, 3200);
  })
</script>
<script type="text/javascript">
  $(function () {
    var saveForm = function() {
      var form = $(this);
      $.ajax({
        url: form.attr("action"),
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function(data) {
          $("#question").html(data.html_code);
        }
      });
      return false;
    };
    $("#question").on("submit", ".js-question-form", saveForm);
  });
</script>
<script>
function submitFunction() {
  document.getElementById("click").click();
}
</script>
{% endblock %}

quiz/core/templates/core/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<form class="form-horizontal" action="{% url 'core:create' %}" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{form|crispy}}
  <button type="submit" name="button">submit</button>
</form>
{% endblock %}

quiz/core/templates/core/partial_question_create.html
<form method="post" action="{% url 'core:create_question' quiz.slug %}" class="js-question-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new question</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'core/partial_question_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create question</button>
  </div>
</form>
<script type="text/javascript">
    $('.myForm').formset();
</script>

quiz/core/templates/core/partial_question_form.html
{% load crispy_forms_tags %}
{{questionform|crispy}}
<br>
<h6>Options</h6>
<div  class="myForm" id="myForm">
  {% for form in formset %}
  {{form}}
  <br>
  {% endfor %}
</div>
{{ formset.management_form }}

quiz/core/templates/core/partial_question_list.html
{% load core_tags %}

{% for question in questions %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h6 class="card-title">Question - {{forloop.counter}}</h6>
    <b>
      <p class="card-text">{{question.question}}</p>
    </b>
  </div>
  {% if question.image %}
  <img class="card-img-top" src="{{ question.image.url }}" alt="Card image cap">
  {% endif %}
  <ul class="list-group list-group-flush">
    {% for option in question.get_options %}
    <li class="list-group-item" style="background:{% question_answer option.id %};">{{option.option}}</li>
    {% endfor %}
  </ul>
  <div class="card-body">
    <button type="button" class="btn btn-warning btn-sm js-update-question" data-url="{% url 'core:edit_question' quiz.slug question.id %}">
      <span class="glyphicon glyphicon-pencil"></span>Edit
    </button>
    <button type="button" class="btn btn-danger btn-sm js-delete-question" data-url="{% url 'core:delete_question' quiz.slug question.id %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
    </button>
  </div>
</div>
<br>
{% empty %}
<div class="">
  <p class="text-center bg-warning">No questions</p>
</div>
{% endfor %}

quiz/core/templates/core/partial_result.html
{% load core_tags %}
<div class="jumbotron" style="margin-top:5px;">
  <div class="row justify-content-center">
    <div class="col">
      <h1>{{quiz.title}}</h1>
      <h6>{{quiz.slug}}</h6>
      <h3>Result---{{response.correct}} out of {{response.total_questions}} correct</h3>
      <div class="card-columns">
      {% for i in record.questions %}
      {% get_question i as question %}
      <div class="card" style="width: 18rem;border:{% question_border forloop.counter response.answers %};">
        <div class="card-body">
          <h6 class="card-title">Question - {{forloop.counter}}</h6>
          <b>
            <p class="card-text" style="color:black;">{{question.question}}</p>
          </b>
        </div>
        {% if question.image %}
        <img class="card-img-top" src="{{ question.image.url }}" alt="Card image cap">
        {% endif %}
        <ul class="list-group list-group-flush">
          {% for option in question.get_options %}
          <li class="list-group-item" style="background:{% option_color forloop.parentloop.counter option.option record.key response.answers %};">{{option.option}}</li>
          {% endfor %}
        </ul>
      </div>
      <br>
      {% endfor %}
    </div>
    <a href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i></a>
  </div>
</div>
</div>

quiz/core/templates/core/quiz_attempt_1.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>Quiz details</h1>
  <h6>{{ quiz.title }} <br>{{ quiz.id }}--{{ quiz.slug }}</h6>
  <div class="container" id = 'form'>
    <form  method="post" id="post-form" action="{% url 'core:attempt_quiz' slug=quiz.slug %}">
      {% csrf_token %}
        {{question.question}} <br>
        <div class="container">
          {% for option in question.get_options %}
            <input type="radio" id="{{option.id}}"  name={{question.id}} value="{{ option.option }}" required>
            <label for="{{option.id}}">{{option.option}}</label><br>
          {% endfor %}
        </div>
      <button type="submit" name="button">Submit</button>
    </form>
  </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
  $(document).on('submit', '#post-form',function(e){
    $.ajax({
        type:'POST',
        url:'{% url 'core:attempt_quiz' slug=quiz.slug %}',
        data:{
            question_response:$('#{{question.id}}').val(),
            record_id:{{record.id}},
            response_id:{{response.id}},
            index : {{index}},
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
        success:function(json){
            $("#post-form").remove();
            $("#form").prepend('<div class="col-md-6">'+
                '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
                    '<div class="col p-4 d-flex flex-column position-static">' +
                        '<h3 class="mb-0">' + json.question.question + '</h3>' +
                    '</div>' +
                '</div>' +
            '</div>'
            )

        },
        error : function(xhr,errmsg,err) {
        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
    }
    });
});
</script>
{% endblock %}

quiz/core/templates/core/quiz_edit.html
{% extends 'base.html' %}
{% load static %}
{% load core_tags %}
{% load crispy_forms_tags %}
{% block content %}
<div class="">
  <h3>Quiz</h3>
  <h6>{{quiz.title}}</h6>
  <hr>
  <p>
    <button type="button" class="btn btn-primary js-create-question"  data-url="{% url 'core:create_question' quiz.slug %}">
      <i class="fa fa-plus" aria-hidden="true"></i>
      New Question
    </button>
  </p>
</div>
<div id='question-list'>
  <div>
    {% include "core/partial_question_list.html" %}
  </div>
</div>
<div class="modal fade" id="modal-question">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script src="{% static 'formset_bootstrap/js/jquery.formset.js' %}"></script>
<script src="{% static 'js/question.js' %}"></script>
<!-- ekkada question.js dhi file peduthey remove ani vasthundhi check chey once -->
<!-- write the above script in the question.js -->
{% endblock %}

quiz/core/templates/core/result.html
{% extends  'base.html' %}
{% load core_tags %}
{% block content %}
<div class="jumbotron">
  <h1>{{quiz.title}}</h1>
  <h6>{{quiz.slug}}</h6>
  <h3>Result---{{response.correct}} out of {{response.total_questions}} correct</h3>
  {% for i in record.questions %}
    {% get_question i as question %}
    <div class="container">
      {{question.question}}
      <div class="container" style="padding-left: 30px;">
        {% for option in question.get_options %}
            <li style="color:{% option_color forloop.parentloop.counter option.option record.key response.answers %};">{{option.option}}</li>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

quiz/core/templates/core/user_quiz_record.html
<style media="screen">
  .thumb1 {
    background: url({{ quiz.image.url }}) 50% 50% no-repeat;
    width: 64px;
    height: 64px;
  }
</style>
<div class="container" style="margin:10px;">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-right:10px;">
    <span aria-hidden="true">&times;</span>
  </button>
  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-body">
          <div class="media">
            <div class="mr-3 rounded thumb1">
            </div>
            <div class="media-body">
              <h4 class="mt-0">{{quiz.title}}</h4>
              {{ quiz.get_total_no_of_questions }} questions
            </div>
          </div>
          <h6>By : {{quiz.author}}</h6>
        </div>
      </div>
      <div class="col">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">NAME</th>
              <th scope="col">POINTS</th>
            </tr>
          </thead>
          <tbody>
            {% for response in responses_all %}
            <tr>
              <td>{{response.record.user}}</td>
              <td>{{response.correct}}/{{response.total_questions}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <br>
      </div>
    </div>
    <div class="col">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">RANK</th>
            <th scope="col">NAME</th>
            <th scope="col">POINTS</th>
          </tr>
        </thead>
        <tbody>
          {% for response in responses %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{response.record.user}}</td>
            <td>{{response.correct}}/{{response.total_questions}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <br>
      <form method="post" action="{% url 'core:attempt_quiz' quiz.slug %}" class="js-quiz-form">
        {% csrf_token %}
        <button type="submit" class="btn btn-success" data>Retake</button>
      </form>
    </div>
  </div>

</div>