quiz/allauth/account/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [

    # default

    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
]

quiz/allauth/socialaccount/providers/agave/urls.py
from allauth.socialaccount.providers.agave.provider import AgaveProvider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(AgaveProvider)

quiz/allauth/socialaccount/providers/asana/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AsanaProvider


urlpatterns = default_urlpatterns(AsanaProvider)

quiz/allauth/socialaccount/providers/auth0/urls.py
# -*- coding: utf-8 -*-
from allauth.socialaccount.providers.auth0.provider import Auth0Provider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(Auth0Provider)

quiz/allauth/socialaccount/providers/azure/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AzureProvider


urlpatterns = default_urlpatterns(AzureProvider)

quiz/allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider


urlpatterns = default_urlpatterns(BaiduProvider)

quiz/allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BitlyProvider


urlpatterns = default_urlpatterns(BitlyProvider)

quiz/allauth/socialaccount/providers/box/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import BoxOAuth2Provider


urlpatterns = default_urlpatterns(BoxOAuth2Provider)

quiz/allauth/socialaccount/providers/cern/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import CernProvider


urlpatterns = default_urlpatterns(CernProvider)

quiz/allauth/socialaccount/providers/daum/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DaumProvider


urlpatterns = default_urlpatterns(DaumProvider)

quiz/allauth/socialaccount/providers/exist/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import ExistProvider


urlpatterns = default_urlpatterns(ExistProvider)

quiz/allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import FirefoxAccountsProvider


urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

quiz/allauth/socialaccount/providers/hubic/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import HubicProvider


urlpatterns = default_urlpatterns(HubicProvider)

quiz/allauth/socialaccount/providers/line/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import LineProvider


urlpatterns = default_urlpatterns(LineProvider)

quiz/allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import VKProvider


urlpatterns = default_urlpatterns(VKProvider)

quiz/allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import XingProvider


urlpatterns = default_urlpatterns(XingProvider)

quiz/allauth/socialaccount/providers/ynab/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import YNABProvider


urlpatterns = default_urlpatterns(YNABProvider)

quiz/allauth/socialaccount/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('login/cancelled/', views.login_cancelled,
         name='socialaccount_login_cancelled'),
    path('login/error/', views.login_error,
         name='socialaccount_login_error'),
    path('signup/', views.signup, name='socialaccount_signup'),
    path('connections/', views.connections, name='socialaccount_connections')
]

quiz/allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings



urlpatterns = [
    path('', include('allauth.account.urls') , name='accounts'),
]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path('social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

quiz/core/urls.py
from django.urls import path
from .views import (
    Test,
    CreateQuiz,
    CreateQuestion,
    AttemptQuiz,
    Result,
    RecordResponse,
    Attempt,
    DeleteQuestion,
    EditQuiz,
    EditQuestion,
    UserQuizRecord,
)

app_name = 'core'

urlpatterns = [
    path('test/', Test.as_view(), name='test'),
    path('create/', CreateQuiz.as_view(), name = 'create'),
    path('edit/<slug>/', EditQuiz.as_view(), name = 'edit_quiz'),

    path('<slug>/create/question/', CreateQuestion.as_view(), name = 'create_question'),
    path('question/<slug>/delete/<id>/', DeleteQuestion.as_view(), name = "delete_question"),
    path('question/<slug>/update/<id>/', EditQuestion.as_view(), name = "edit_question"),

    path('record/user/<slug>', UserQuizRecord.as_view(), name= 'user_quiz_record'),

    path('attempt/<slug>/', AttemptQuiz.as_view(), name = 'attempt_quiz'),
    path('attempt1/<slug>/<int:id>/<int:index>/', Attempt.as_view(), name = 'attempt'),

    path('result/<slug>/<id>/', Result.as_view(), name = 'quiz_result'),
    path('record_response/', RecordResponse.as_view(), name = 'ajax_record_response'),

]

quiz/profiles/urls.py
from django.urls import path,include
from . import views

app_name='profiles'

urlpatterns = [
    path('edit/',views.ProfileUpdate.as_view() , name='profile_update'),
    path('image-edit/',views.DpUpdate.as_view() , name='dp_update'),
    path('<slug>',views.ProfileView.as_view() , name='profile'),
]

quiz/quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import (
     Home,
     about,
     Setting,
     Activity,
     Completed,
     Created,
     autoCompleteView,
     searchAutoComplete,
     Search,

)

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('profile/',include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('quiz/', include("core.urls")),
    path('about/', about , name = 'about'),
    path('settings/', Setting.as_view(), name='setting'),
    path('activity/', Activity.as_view(), name= 'activity'),
    path('completed/', Completed.as_view(), name= 'completed'),
    path('created/', Created.as_view(), name = 'created'),

    path('search/', Search.as_view(), name='search'),
    path('autocomplete/', autoCompleteView, name='autocomplete'),
    path('search-autocomplete/', searchAutoComplete, name='search-autocomplete'),
    path('', Home.as_view(), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

quiz/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  {% if title %}
  <title> Quiz - {{ title }}</title>
  {% else %}
  <title>Intrugue</title>
  {% endif %}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

  <!-- highlight-js plugins-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
  <link rel="stylesheet" type="text/css" href="{% static 'androidstudio.css' %}">
  <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
  <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/material-icons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Pretty-Header.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Article-Cards1.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Header-Dark1.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Article.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">



  <!-- below link for article list css -->
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"> -->

  {% block custom_css %}{% endblock %}

<body onresize="col_width()">
  <div class="header-dark navbar-fixed-top">
    <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search home">
      <div class="container"><a class="navbar-brand" href="{% url "home" %}">Quiz</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav">
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "home" %}">Home</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "about" %}">About</a></li>
            <!-- <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Dropdown </a>
              <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation"
                  href="#">Third Item</a></div>
            </li> -->
          </ul>
          <form class="form-inline mr-auto" target="_self" action="{% url 'search' %}" method="GET">
            <div class="form-group">
              <label for="search"><i class="material-icons">search</i></label>
              <input class="form-control search-field" type="search" id="search" name="q">
            </div>
          </form>
            <ul class="nav navbar-nav ml-auto">
              <li class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"> <img class="dropdown-image" src="{{ user.profileimage.profile_image.url }}"></a>
                <div class="dropdown-menu dropdown-menu-right" role="menu">
                  <a class="dropdown-item" role="presentation" href="{% url 'core:create' %}">New quiz</a>
                  <a class="dropdown-item" role="presentation" href="{% url 'activity' %}">Activity</a>
                  <a class="dropdown-item" role="presentation" href="{% url 'profiles:profile' slug=user.username %}">Profile </a>
                  <a class="dropdown-item" role="presentation" href="{% url 'setting' %}">Settings</a>
                  <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item" role="presentation">Sign Out</button>
                  </form>
                </div>
                {% else %}
                <span class="navbar-text">
                  <a class="login" href="{% url 'account_login' %}">Log In</a>
                  <a  class="login" href="{% url 'account_signup' %}">Sign Up</a>
                </span>
                {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </nav>
  </div>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
  </main>
  <div class="container content">{% block content %}{% endblock %}</div>
  {% block content1 %}{% endblock %}
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://www.jqueryscript.net/demo/Tiny-Text-Field-Based-Tags-Input-Plugin-For-jQuery-Tagify/jQuery.tagify.js">  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="{% static 'assets/js/masonry.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="{% static 'js/cropper.min.js' %}"></script>
  <script src="{% static 'assets/js/header-search.js' %}"></script>
  <script type="text/javascript">
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
  </script>
<script type="text/javascript">
  $(function() {
    $("#search").autocomplete({
      source: '{% url 'search-autocomplete' %}'
    });
  });
</script>
<script type="text/javascript">
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 260,
    isFitWidth: true
  });
</script>
<script type="text/javascript">
  $('.grid1').masonry({
    itemSelector: '.grid-item',
    columnWidth: 100,
    isFitWidth: true
  });
</script>

{% block custom_js %}{% endblock %}
</body>
</html>

quiz/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  {% if title %}
  <title> Quiz - {{ title }}</title>
  {% else %}
  <title>Intrugue</title>
  {% endif %}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

  <!-- highlight-js plugins-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
  <link rel="stylesheet" type="text/css" href="{% static 'androidstudio.css' %}">
  <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
  <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/material-icons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Pretty-Header.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Header-Dark1.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Article.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/Article-Cards1.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


  <!-- below link for article list css -->
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"> -->

  {% block custom_css %}{% endblock %}

<body onresize="col_width()">
  <div class="header-dark navbar-fixed-top">
    <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search home">
      <div class="container"><a class="navbar-brand" href="{% url "home" %}">Quiz</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav">
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "home" %}">Home</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url "about" %}">About</a></li>
            <!-- <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Dropdown </a>
              <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation"
                  href="#">Third Item</a></div>
            </li> -->
          </ul>
          <form class="form-inline mr-auto" target="_self" action="" method="GET">
            <div class="form-group">
              <label for="search"><i class="material-icons">search</i></label>
              <input class="form-control search-field" type="search" id="search" name="q">
            </div>
          </form>
            <ul class="nav navbar-nav ml-auto">
              <li class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"> <img class="dropdown-image" src="{{ user.profileimage.profile_image.url }}"></a>
                <div class="dropdown-menu dropdown-menu-right" role="menu">
                  <a class="dropdown-item" role="presentation" href="{% url 'core:create' %}">New Quiz </a>
                  <a class="dropdown-item" role="presentation" href="{% url 'activity' %}">Activity</a>

                  <a class="dropdown-item" role="presentation" href="{% url 'profiles:profile' slug=user.username %}">Profile </a>
                  <a class="dropdown-item" role="presentation" href="{% url 'setting' %}">Settings</a>
                  <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item" role="presentation">Sign Out</button>
                  </form>
                </div>
                {% else %}
                <span class="navbar-text">
                  <a class="login" href="{% url 'account_login' %}">Log In</a>
                  <a  class="login" href="{% url 'account_signup' %}">Sign Up</a>
                </span>
                {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container content">{% block content %}{% endblock %}</div>
  {% block content1 %}{% endblock %}
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="{% static 'assets/js/masonry.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="{% static 'js/cropper.min.js' %}"></script>
  <script src="{% static 'assets/js/header-search.js' %}"></script>
  <script type="text/javascript">
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
  </script>
<script type="text/javascript">
  $(function() {
    $("#search").autocomplete({
      source: '#'
    });
  });
</script>
<script type="text/javascript">
  function col_width() {
    var x = window.matchMedia("(max-width: 370px)");
    if (x.matches) {
      x = 270;
    } else {
      x = 310;
    }
  $('.grid').masonry({
    itemSelector: '.article',
    columnWidth: x,
    isFitWidth: true
  });
 }
</script>
<script type="text/javascript">
    var x = window.matchMedia("(max-width: 370px)");
    if (x.matches) {
      x=270;
    } else {
      x=310;
    }
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: x,
    isFitWidth: true
  });
</script>
<script type="text/javascript">
  $('.grid1').masonry({
    itemSelector: '.grid-item',
    columnWidth: 100,
    isFitWidth: true
  });
</script>
{% block custom_js %}{% endblock %}
</body>

</html>

quiz/templates/searchresult.html
{% extends "base.html" %}
{% load static %}
{% load active_class %}
{% block content %}
<legend class="border-bottom mb-4">{% get_query request %}--Results : {{ length }}</legend>
{% if quizes|length %}
<div class="jumbotron">
  <div class="grid" id="quiz-list">
    {% for quiz in quizes %}
    <button type="button"  class="js-grid-item" data-url="{% url 'core:attempt_quiz' slug=quiz.slug %}">
    <div class="grid-item">
      <div class="card" style="width: 250px;margin : 4px;">
        {% if quiz.image %}
        <img src="{{ quiz.image.url }}" class="card-img-top" alt="quiz_image">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ quiz.title }}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    </button>
    {% endfor %}
  </div>
</div>
{% elif users|length %}
<div class="jumbotron">
  <div class="grid1" >
    {% for user in users %}
    <div class="grid-item">
      <div class="our-team">
        <div class="picture">
          <a href="{% url 'profiles:profile' slug=user.username %}"><img class="img-fluid" src="{{ user.profileimage.profile_image.url }}"></a>
        </div>
        <div class="team-content">
          <h5 class="name">{{ user.username }}</h5>
          {% if user.profile.role %}
          <h6 class="title">{{ user.profile.role }}</h6>
          {% endif %}
        </div>
        <ul class="social">
          {% if user.email %}
          <li><a href="mailto:{{ user.email }}" class="fa fa-envelope-square" aria-hidden="true"></a></li>
          {% endif %}
          {% if user.profile.linkedin %}
          <li><a href="{{ user.profile.linkedin }}" class="fa fa-linkedin" aria-hidden="true"></a></li>
          {% endif %}
          {% if user.profile.twitter %}
          <li><a href="{{ user.profile.twitter }}" class="fa fa-twitter" aria-hidden="true"></a></li>
          {% endif %}
          {% if user.profile.github %}
          <li><a href="{{ user.profile.github }}" class="fa fa-github" aria-hidden="true"></a></li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}
<div class="modal fade" id="modal-quiz">
  <div class="modal-dialog modal-xl">
    <div class="modal-content"></div>
  </div>
</div>
{% endblock content %}
{% block custom_js %}
<script type="text/javascript">
  $(function() {
    var loadForm = function() {
      var btn = $(this);
      $.ajax({
        url: btn.attr("data-url"),
        type: 'get',
        dataType: 'json',
        beforeSend: function() {
          $("#modal-quiz").modal("show");
        },
        success: function(data) {
          $("#modal-quiz .modal-content").html(data.html_code);
        }
      });
    };
    $("#quiz-list").on("click", ".js-grid-item", loadForm);
  });
</script>
{% endblock %}